### ISSUE TITLE
Detach fork? 

### ISSUE THREAD

**Issue by jefftriplett** [pfouque/django-fsm-2#17]
Hi, I wanted to express my appreciation for your work in forking and maintaining django-fsm-2 

I was curious if you had looked into detaching your fork from the original project. See: https://support.github.com/request/fork

Detaching your fork from the original project not only allows you to retain your stars, followers, issues, etc, but also helps establish the project as a standalone entity, rather than just another fork. 

Selfishly, this would help us out at Django Packages, too. We'd like to track the project, but we receive so many forks of official reports that there are a bunch of checks that are skipped when someone submits a fork. We'll work on addressing this either way, but I thought I'd ask in case you hadn't considered it yet. https://djangopackages.org/packages/p/django-fsm-2/ 

Thanks again for the work and your consideration!

**Comment by pfouque** [comment]
Hi @jefftriplett,

Thanks for your notice (and warm words), It's now detached!

Have a nice day!
